#!/bin/bash

# Name of the dataset
name_dataset='seri'
# Input path
input_path='/work/le2i/gu5306le/retinopathy/OCT/SERI/feature_data/flatten/lbp_riu/lbp_hist/lbp_local'
# Output path
output_path='/work/le2i/gu5306le/retinopathy/OCT/SERI/results/flatten/lbp_riu/lbp_hist/lbp_local'
# Type of codebook
codebook_type='codebook_random'

# Keep the directory of the script into a variable
script_dir=$(pwd)

# Try the three different radius
for radius in `seq 1 3`;
do
    # Create an automatic script
    script_filename_core='/script_lbp_flatten_local_random_r_'
    script_filename="$script_dir$script_filename_core$radius"
    ### Create the file
    touch $script_filename
    ### Truncate the file if it is existing
    : > $script_filename
    
    printf "ipython ../../pipeline/feature-classification/${name_dataset}/classification_lbp_bow.py ${radius} \"${input_path}\" \"${output_path}\" \"${codebook_type}\" " >> $script_filename
    ### Make it executable
    chmod u+x $script_filename
    # Submit the job to the queue
    qsub -q batch -pe smp 8 $script_filename
done
