#!/bin/bash

# # USAGE:
# if [ "$#" != "1" ];
# then
#     echo "**************************************************************"
#     echo "Usage:"
#     echo "./extraction_random_codebook dataPath"
#     echo
#     echo "Example: ./extraction_random_codebook radius ~/Home/Data"
#     echo " "
#     echo "Current entry: $0 $*"
#     echo "**************************************************************"
#     echo " "

#     exit
# fi

# # Affect the input folder for the data
# data_path=$1

# radius=1

# str_path_npz="/work/le2i/gu5306le/retinopathy/OCT/SERI/feature_data/flatten/lbp_org/lbp_hist/lbp_local/r_${radius}_hist_npz"
# str_path_mat="/work/le2i/gu5306le/retinopathy/OCT/SERI/feature_data/flatten/lbp_org/lbp_hist/lbp_local/r_${radius}_hist_mat"

# # Keep the directory of the script into a variable
# script_dir=$(pwd)

# # Move to the right directory for the processing
# #cd "/user1/le2i/gu5306le/Work/protoclass"

# # Submit a job for each patient
# patient_idx=0
# for patient in $data_path*; do
#     # Create an automatic script
#     script_filename_core='/script_r_'
#     script_filename="$script_dir$script_filename_core$radius$patient_idx"
#     ### Create the file
#     touch $script_filename
#     ### Truncate the file if it is existing
#     : > $script_filename
#     ### Write the command to execute
#     printf "ipython ../../pipeline/feature-detection/detection_lbp_histogram_non_overlap_win.py \"${patient%/}\" \"$str_path_npz\" \"$str_path_mat\"" >> $script_filename
#     ### Make it executable
#     chmod u+x $script_filename
#     # Submit the job to the queue
#     #bash $script_filename
#     qsub -q batch -pe smp 8 $script_filename
#     ((patient_idx++))
# done

radius=$1
data_path=$2

# Keep the directory of the script into a variable
script_dir=$(pwd)
# Create an automatic script
script_filename_core='/script_cropped_lbptop_r_'
script_filename="$script_dir$script_filename_core$radius$patient_idx"
### Create the file
touch $script_filename
### Truncate the file if it is existing
: > $script_filename

printf "ipython ../../pipeline/feature-extraction/extraction_random_codebook.py ${radius} \"${data_path}\" " >> $script_filename
### Make it executable
chmod u+x $script_filename
# Submit the job to the queue
qsub -q batch -pe smp 8 $script_filename
