#!/bin/bash

# Name of the dataset
name_dataset='seri'
# Input path
input_path='/work/le2i/gu5306le/retinopathy/OCT/SERI/feature_data/non_flatten/lbp_riu/lbp_hist/lbp_global'
# Output path
# output_path='/work/le2i/gu5306le/retinopathy/OCT/SERI/results/non_flatten/lbp_riu/lbp_hist/lbp_local'
# Type of codebook
# codebook_type='codebook_random'

# Keep the directory of the script into a variable
script_dir=$(pwd)

for radius in `seq 1 3`;
do
    # Create an automatic script
    script_filename_core='/script_lbp_non_flatten_global_random_r_'
    script_filename="$script_dir$script_filename_core$radius"
    ### Create the file
    touch $script_filename
    ### Truncate the file if it is existing
    : > $script_filename
    
    printf "ipython ../../pipeline/feature-extraction/${name_dataset}/extraction_lbp_codebook_global_random.py ${radius} \"${input_path}\" " >> $script_filename
    ### Make it executable
    chmod u+x $script_filename
    # Submit the job to the queue
    qsub -q batch -pe smp 8 $script_filename
done
